### ISSUE TITLE
Recreate 'OCS Canister' as SVG

### ISSUE THREAD

**Issue by VanFossen** [RastonLab/Virtual-HeNDI-Spectrometer#20]
[Link to repo to update/store SVGs and Inkscape tutorial resources](https://github.com/RastonLab/Virtual-Instruments/wiki#repository-for-spectrometer-svgs)

**Comment by spectroscopy** [comment]
updated design:
![image](https://user-images.githubusercontent.com/75122115/173075952-8a9c847e-81ab-4eb9-8cde-b9f01fb83460.png)
