### ISSUE TITLE
Recreate 'Stark' as SVG

### ISSUE THREAD

**Issue by VanFossen** [RastonLab/Virtual-HeNDI-Spectrometer#22]
[Link to repo to update/store SVGs and Inkscape tutorial resources](https://github.com/RastonLab/Virtual-Instruments/wiki#repository-for-spectrometer-svgs)

**Comment by spectroscopy** [comment]
Here's the actual one (rotated 180 deg):
![Image](https://user-images.githubusercontent.com/75122115/173111876-d05d5cdb-5703-4419-834d-36f6a2a4693b.png)
