### ISSUE TITLE
Create 'Salt Window' as SVG

### ISSUE THREAD

**Issue by VanFossen** [RastonLab/Virtual-HeNDI-Spectrometer#27]
[Link to repo to update/store SVGs and Inkscape tutorial resources](https://github.com/RastonLab/Virtual-Instruments/wiki#repository-for-spectrometer-svgs)

**Comment by spectroscopy** [comment]
Here's a close up of the flange + salt window (rotated 90 deg):
![Image](https://user-images.githubusercontent.com/75122115/173100330-dff24400-8312-4832-8ccf-bea0702a4326.png)
