### ISSUE TITLE
Updated text within the HeNDI application

### ISSUE THREAD

**Issue by spectroscopy** [RastonLab/Virtual-HeNDI-Spectrometer#4]
- "Run Spectrum" should be "Collect Spectrum".
- After clicking "Collect Spectrum.", instead of "Loading..." it should read "Preparing instrument"
- Instead of showing whole spectrum at once it should gradually appear from low to high Wavenumber (note "Wavelength" needs to be renamed to "Wavenumber") at a rate of ~10 cm-1/min (This may not be possible and practical. Look into)

**Comment by ronalgomezjmu** [comment]
#Once the graph has been zoomed into, there is no way to zoom out. Fix eventually.
