### ISSUE TITLE
Add new components to HeNDI (descriptions here!)

### ISSUE THREAD

**Issue by hcientist** [RastonLab/Virtual-HeNDI-Spectrometer#7]
Using the documentation here: https://github.com/RastonLab/Virtual-HeNDI-Spectrometer/issues/2

**NEEDS TO BE BROKEN DOWN MORE**
- Drawing of actual components?
- Hover text?
- Interior views?
- (possibly more)

Add new components
- Ion Gauge (3)
- Diffusion Pump (2)
- Turbo Pump
- Rotary Pump
- Salt Window
- Laser Symbol

![Image](https://user-images.githubusercontent.com/35882058/171455204-e1ff2467-d7ce-4202-b3aa-442ff56e5589.jpg)

**Comment by hcientist** [comment]
@spectroscopy please let us know what text should appear when hovering on the new components

**Comment by spectroscopy** [comment]
Changes to existing text:

Detection Chamber:
Houses a mass spectrometer which is used to detect helium nanodroplets.

Source Chamber:
This is where helium nanodroplets are formed.

Quadrupole Mass Spectrometer:
This instrument ionizes helium nanodroplets, and deflects the charged fragments through a [quadrupole mass analyzer](https://en.wikipedia.org/wiki/Quadrupole_mass_analyzer) (mass filter), and to an [electro multiplier tube](https://en.wikipedia.org/wiki/Electron_multiplier). The output is processed with a [lock-in amplifier](https://en.wikipedia.org/wiki/Lock-in_amplifier) that is referenced to the frequency of the chopper wheel.
